//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IPDetectServer.Repositories
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DataEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DataEntities”部分中的连接字符串初始化新 DataEntities 对象。
        /// </summary>
        public DataEntities() : base("name=DataEntities", "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DataEntities 对象。
        /// </summary>
        public DataEntities(string connectionString) : base(connectionString, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DataEntities 对象。
        /// </summary>
        public DataEntities(EntityConnection connection) : base(connection, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<IPEntity> IPEntities
        {
            get
            {
                if ((_IPEntities == null))
                {
                    _IPEntities = base.CreateObjectSet<IPEntity>("IPEntities");
                }
                return _IPEntities;
            }
        }
        private ObjectSet<IPEntity> _IPEntities;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<LoginRecord> LoginRecords
        {
            get
            {
                if ((_LoginRecords == null))
                {
                    _LoginRecords = base.CreateObjectSet<LoginRecord>("LoginRecords");
                }
                return _LoginRecords;
            }
        }
        private ObjectSet<LoginRecord> _LoginRecords;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ServerSetting> ServerSettings
        {
            get
            {
                if ((_ServerSettings == null))
                {
                    _ServerSettings = base.CreateObjectSet<ServerSetting>("ServerSettings");
                }
                return _ServerSettings;
            }
        }
        private ObjectSet<ServerSetting> _ServerSettings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<token> Tokens
        {
            get
            {
                if ((_Tokens == null))
                {
                    _Tokens = base.CreateObjectSet<token>("Tokens");
                }
                return _Tokens;
            }
        }
        private ObjectSet<token> _Tokens;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RouteData> RouteDatas
        {
            get
            {
                if ((_RouteDatas == null))
                {
                    _RouteDatas = base.CreateObjectSet<RouteData>("RouteDatas");
                }
                return _RouteDatas;
            }
        }
        private ObjectSet<RouteData> _RouteDatas;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ClientIP> ClientIPs
        {
            get
            {
                if ((_ClientIPs == null))
                {
                    _ClientIPs = base.CreateObjectSet<ClientIP>("ClientIPs");
                }
                return _ClientIPs;
            }
        }
        private ObjectSet<ClientIP> _ClientIPs;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 IPEntities EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToIPEntities(IPEntity iPEntity)
        {
            base.AddObject("IPEntities", iPEntity);
        }
    
        /// <summary>
        /// 用于向 LoginRecords EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToLoginRecords(LoginRecord loginRecord)
        {
            base.AddObject("LoginRecords", loginRecord);
        }
    
        /// <summary>
        /// 用于向 ServerSettings EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToServerSettings(ServerSetting serverSetting)
        {
            base.AddObject("ServerSettings", serverSetting);
        }
    
        /// <summary>
        /// 用于向 Tokens EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTokens(token token)
        {
            base.AddObject("Tokens", token);
        }
    
        /// <summary>
        /// 用于向 RouteDatas EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRouteDatas(RouteData routeData)
        {
            base.AddObject("RouteDatas", routeData);
        }
    
        /// <summary>
        /// 用于向 Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// 用于向 ClientIPs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToClientIPs(ClientIP clientIP)
        {
            base.AddObject("ClientIPs", clientIP);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="ClientIP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientIP : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ClientIP 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static ClientIP CreateClientIP(global::System.Int32 id)
        {
            ClientIP clientIP = new ClientIP();
            clientIP.ID = id;
            return clientIP;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientPublicIP
        {
            get
            {
                return _ClientPublicIP;
            }
            set
            {
                OnClientPublicIPChanging(value);
                ReportPropertyChanging("ClientPublicIP");
                _ClientPublicIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientPublicIP");
                OnClientPublicIPChanged();
            }
        }
        private global::System.String _ClientPublicIP;
        partial void OnClientPublicIPChanging(global::System.String value);
        partial void OnClientPublicIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientPrivateIP
        {
            get
            {
                return _ClientPrivateIP;
            }
            set
            {
                OnClientPrivateIPChanging(value);
                ReportPropertyChanging("ClientPrivateIP");
                _ClientPrivateIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientPrivateIP");
                OnClientPrivateIPChanged();
            }
        }
        private global::System.String _ClientPrivateIP;
        partial void OnClientPrivateIPChanging(global::System.String value);
        partial void OnClientPrivateIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubmitFromServerIP
        {
            get
            {
                return _SubmitFromServerIP;
            }
            set
            {
                OnSubmitFromServerIPChanging(value);
                ReportPropertyChanging("SubmitFromServerIP");
                _SubmitFromServerIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubmitFromServerIP");
                OnSubmitFromServerIPChanged();
            }
        }
        private global::System.String _SubmitFromServerIP;
        partial void OnSubmitFromServerIPChanging(global::System.String value);
        partial void OnSubmitFromServerIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientProvince
        {
            get
            {
                return _ClientProvince;
            }
            set
            {
                OnClientProvinceChanging(value);
                ReportPropertyChanging("ClientProvince");
                _ClientProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientProvince");
                OnClientProvinceChanged();
            }
        }
        private global::System.String _ClientProvince;
        partial void OnClientProvinceChanging(global::System.String value);
        partial void OnClientProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientCity
        {
            get
            {
                return _ClientCity;
            }
            set
            {
                OnClientCityChanging(value);
                ReportPropertyChanging("ClientCity");
                _ClientCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientCity");
                OnClientCityChanged();
            }
        }
        private global::System.String _ClientCity;
        partial void OnClientCityChanging(global::System.String value);
        partial void OnClientCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientDistinct
        {
            get
            {
                return _ClientDistinct;
            }
            set
            {
                OnClientDistinctChanging(value);
                ReportPropertyChanging("ClientDistinct");
                _ClientDistinct = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientDistinct");
                OnClientDistinctChanged();
            }
        }
        private global::System.String _ClientDistinct;
        partial void OnClientDistinctChanging(global::System.String value);
        partial void OnClientDistinctChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientDetailAddr
        {
            get
            {
                return _ClientDetailAddr;
            }
            set
            {
                OnClientDetailAddrChanging(value);
                ReportPropertyChanging("ClientDetailAddr");
                _ClientDetailAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientDetailAddr");
                OnClientDetailAddrChanged();
            }
        }
        private global::System.String _ClientDetailAddr;
        partial void OnClientDetailAddrChanging(global::System.String value);
        partial void OnClientDetailAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpectedOperatorProvince
        {
            get
            {
                return _ExpectedOperatorProvince;
            }
            set
            {
                OnExpectedOperatorProvinceChanging(value);
                ReportPropertyChanging("ExpectedOperatorProvince");
                _ExpectedOperatorProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpectedOperatorProvince");
                OnExpectedOperatorProvinceChanged();
            }
        }
        private global::System.String _ExpectedOperatorProvince;
        partial void OnExpectedOperatorProvinceChanging(global::System.String value);
        partial void OnExpectedOperatorProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpectedOperatorCity
        {
            get
            {
                return _ExpectedOperatorCity;
            }
            set
            {
                OnExpectedOperatorCityChanging(value);
                ReportPropertyChanging("ExpectedOperatorCity");
                _ExpectedOperatorCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpectedOperatorCity");
                OnExpectedOperatorCityChanged();
            }
        }
        private global::System.String _ExpectedOperatorCity;
        partial void OnExpectedOperatorCityChanging(global::System.String value);
        partial void OnExpectedOperatorCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpectedOperator
        {
            get
            {
                return _ExpectedOperator;
            }
            set
            {
                OnExpectedOperatorChanging(value);
                ReportPropertyChanging("ExpectedOperator");
                _ExpectedOperator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpectedOperator");
                OnExpectedOperatorChanged();
            }
        }
        private global::System.String _ExpectedOperator;
        partial void OnExpectedOperatorChanging(global::System.String value);
        partial void OnExpectedOperatorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealOperatorProvince
        {
            get
            {
                return _RealOperatorProvince;
            }
            set
            {
                OnRealOperatorProvinceChanging(value);
                ReportPropertyChanging("RealOperatorProvince");
                _RealOperatorProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealOperatorProvince");
                OnRealOperatorProvinceChanged();
            }
        }
        private global::System.String _RealOperatorProvince;
        partial void OnRealOperatorProvinceChanging(global::System.String value);
        partial void OnRealOperatorProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealOperatorCity
        {
            get
            {
                return _RealOperatorCity;
            }
            set
            {
                OnRealOperatorCityChanging(value);
                ReportPropertyChanging("RealOperatorCity");
                _RealOperatorCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealOperatorCity");
                OnRealOperatorCityChanged();
            }
        }
        private global::System.String _RealOperatorCity;
        partial void OnRealOperatorCityChanging(global::System.String value);
        partial void OnRealOperatorCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealOperator
        {
            get
            {
                return _RealOperator;
            }
            set
            {
                OnRealOperatorChanging(value);
                ReportPropertyChanging("RealOperator");
                _RealOperator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealOperator");
                OnRealOperatorChanged();
            }
        }
        private global::System.String _RealOperator;
        partial void OnRealOperatorChanging(global::System.String value);
        partial void OnRealOperatorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int64> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int64> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientRecordor
        {
            get
            {
                return _ClientRecordor;
            }
            set
            {
                OnClientRecordorChanging(value);
                ReportPropertyChanging("ClientRecordor");
                _ClientRecordor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientRecordor");
                OnClientRecordorChanged();
            }
        }
        private global::System.String _ClientRecordor;
        partial void OnClientRecordorChanging(global::System.String value);
        partial void OnClientRecordorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="IPEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IPEntity : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 IPEntity 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="iPStart">IPStart 属性的初始值。</param>
        /// <param name="iPEnd">IPEnd 属性的初始值。</param>
        public static IPEntity CreateIPEntity(global::System.Int32 id, global::System.String iPStart, global::System.String iPEnd)
        {
            IPEntity iPEntity = new IPEntity();
            iPEntity.ID = id;
            iPEntity.IPStart = iPStart;
            iPEntity.IPEnd = iPEnd;
            return iPEntity;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPStart
        {
            get
            {
                return _IPStart;
            }
            set
            {
                OnIPStartChanging(value);
                ReportPropertyChanging("IPStart");
                _IPStart = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPStart");
                OnIPStartChanged();
            }
        }
        private global::System.String _IPStart;
        partial void OnIPStartChanging(global::System.String value);
        partial void OnIPStartChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPEnd
        {
            get
            {
                return _IPEnd;
            }
            set
            {
                OnIPEndChanging(value);
                ReportPropertyChanging("IPEnd");
                _IPEnd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPEnd");
                OnIPEndChanged();
            }
        }
        private global::System.String _IPEnd;
        partial void OnIPEndChanging(global::System.String value);
        partial void OnIPEndChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPBelongTo
        {
            get
            {
                return _IPBelongTo;
            }
            set
            {
                OnIPBelongToChanging(value);
                ReportPropertyChanging("IPBelongTo");
                _IPBelongTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPBelongTo");
                OnIPBelongToChanged();
            }
        }
        private global::System.String _IPBelongTo;
        partial void OnIPBelongToChanging(global::System.String value);
        partial void OnIPBelongToChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IPStartNum
        {
            get
            {
                return _IPStartNum;
            }
            set
            {
                OnIPStartNumChanging(value);
                ReportPropertyChanging("IPStartNum");
                _IPStartNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IPStartNum");
                OnIPStartNumChanged();
            }
        }
        private Nullable<global::System.Int64> _IPStartNum;
        partial void OnIPStartNumChanging(Nullable<global::System.Int64> value);
        partial void OnIPStartNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IPEndNum
        {
            get
            {
                return _IPEndNum;
            }
            set
            {
                OnIPEndNumChanging(value);
                ReportPropertyChanging("IPEndNum");
                _IPEndNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IPEndNum");
                OnIPEndNumChanged();
            }
        }
        private Nullable<global::System.Int64> _IPEndNum;
        partial void OnIPEndNumChanging(Nullable<global::System.Int64> value);
        partial void OnIPEndNumChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="LoginRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoginRecord : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 LoginRecord 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static LoginRecord CreateLoginRecord(global::System.Int32 id)
        {
            LoginRecord loginRecord = new LoginRecord();
            loginRecord.ID = id;
            return loginRecord;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LoginDate
        {
            get
            {
                return _LoginDate;
            }
            set
            {
                OnLoginDateChanging(value);
                ReportPropertyChanging("LoginDate");
                _LoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginDate");
                OnLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LoginDate;
        partial void OnLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLoginDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginIP
        {
            get
            {
                return _LoginIP;
            }
            set
            {
                OnLoginIPChanging(value);
                ReportPropertyChanging("LoginIP");
                _LoginIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoginIP");
                OnLoginIPChanged();
            }
        }
        private global::System.String _LoginIP;
        partial void OnLoginIPChanging(global::System.String value);
        partial void OnLoginIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IsLoginFromClient
        {
            get
            {
                return _IsLoginFromClient;
            }
            set
            {
                OnIsLoginFromClientChanging(value);
                ReportPropertyChanging("IsLoginFromClient");
                _IsLoginFromClient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLoginFromClient");
                OnIsLoginFromClientChanged();
            }
        }
        private Nullable<global::System.Int64> _IsLoginFromClient;
        partial void OnIsLoginFromClientChanging(Nullable<global::System.Int64> value);
        partial void OnIsLoginFromClientChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="RouteData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RouteData : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RouteData 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="groupID">GroupID 属性的初始值。</param>
        public static RouteData CreateRouteData(global::System.Int32 id, global::System.Int32 groupID)
        {
            RouteData routeData = new RouteData();
            routeData.ID = id;
            routeData.GroupID = groupID;
            return routeData;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeqNoInGroup
        {
            get
            {
                return _SeqNoInGroup;
            }
            set
            {
                OnSeqNoInGroupChanging(value);
                ReportPropertyChanging("SeqNoInGroup");
                _SeqNoInGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeqNoInGroup");
                OnSeqNoInGroupChanged();
            }
        }
        private Nullable<global::System.Int32> _SeqNoInGroup;
        partial void OnSeqNoInGroupChanging(Nullable<global::System.Int32> value);
        partial void OnSeqNoInGroupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String T1
        {
            get
            {
                return _T1;
            }
            set
            {
                OnT1Changing(value);
                ReportPropertyChanging("T1");
                _T1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("T1");
                OnT1Changed();
            }
        }
        private global::System.String _T1;
        partial void OnT1Changing(global::System.String value);
        partial void OnT1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String T2
        {
            get
            {
                return _T2;
            }
            set
            {
                OnT2Changing(value);
                ReportPropertyChanging("T2");
                _T2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("T2");
                OnT2Changed();
            }
        }
        private global::System.String _T2;
        partial void OnT2Changing(global::System.String value);
        partial void OnT2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String T3
        {
            get
            {
                return _T3;
            }
            set
            {
                OnT3Changing(value);
                ReportPropertyChanging("T3");
                _T3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("T3");
                OnT3Changed();
            }
        }
        private global::System.String _T3;
        partial void OnT3Changing(global::System.String value);
        partial void OnT3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteIP
        {
            get
            {
                return _RouteIP;
            }
            set
            {
                OnRouteIPChanging(value);
                ReportPropertyChanging("RouteIP");
                _RouteIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RouteIP");
                OnRouteIPChanged();
            }
        }
        private global::System.String _RouteIP;
        partial void OnRouteIPChanging(global::System.String value);
        partial void OnRouteIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPBelongTo
        {
            get
            {
                return _IPBelongTo;
            }
            set
            {
                OnIPBelongToChanging(value);
                ReportPropertyChanging("IPBelongTo");
                _IPBelongTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPBelongTo");
                OnIPBelongToChanged();
            }
        }
        private global::System.String _IPBelongTo;
        partial void OnIPBelongToChanging(global::System.String value);
        partial void OnIPBelongToChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RouteDate
        {
            get
            {
                return _RouteDate;
            }
            set
            {
                OnRouteDateChanging(value);
                ReportPropertyChanging("RouteDate");
                _RouteDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RouteDate");
                OnRouteDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RouteDate;
        partial void OnRouteDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRouteDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPBelongToProvince
        {
            get
            {
                return _IPBelongToProvince;
            }
            set
            {
                OnIPBelongToProvinceChanging(value);
                ReportPropertyChanging("IPBelongToProvince");
                _IPBelongToProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPBelongToProvince");
                OnIPBelongToProvinceChanged();
            }
        }
        private global::System.String _IPBelongToProvince;
        partial void OnIPBelongToProvinceChanging(global::System.String value);
        partial void OnIPBelongToProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPBelongToCity
        {
            get
            {
                return _IPBelongToCity;
            }
            set
            {
                OnIPBelongToCityChanging(value);
                ReportPropertyChanging("IPBelongToCity");
                _IPBelongToCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPBelongToCity");
                OnIPBelongToCityChanged();
            }
        }
        private global::System.String _IPBelongToCity;
        partial void OnIPBelongToCityChanging(global::System.String value);
        partial void OnIPBelongToCityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="ServerSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ServerSetting : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ServerSetting 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="serverName">ServerName 属性的初始值。</param>
        /// <param name="serverType">ServerType 属性的初始值。</param>
        /// <param name="iP">IP 属性的初始值。</param>
        public static ServerSetting CreateServerSetting(global::System.Int32 id, global::System.String serverName, global::System.Int32 serverType, global::System.String iP)
        {
            ServerSetting serverSetting = new ServerSetting();
            serverSetting.ID = id;
            serverSetting.ServerName = serverName;
            serverSetting.ServerType = serverType;
            serverSetting.IP = iP;
            return serverSetting;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ServerName
        {
            get
            {
                return _ServerName;
            }
            set
            {
                OnServerNameChanging(value);
                ReportPropertyChanging("ServerName");
                _ServerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ServerName");
                OnServerNameChanged();
            }
        }
        private global::System.String _ServerName;
        partial void OnServerNameChanging(global::System.String value);
        partial void OnServerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ServerType
        {
            get
            {
                return _ServerType;
            }
            set
            {
                OnServerTypeChanging(value);
                ReportPropertyChanging("ServerType");
                _ServerType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServerType");
                OnServerTypeChanged();
            }
        }
        private global::System.Int32 _ServerType;
        partial void OnServerTypeChanging(global::System.Int32 value);
        partial void OnServerTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DNS
        {
            get
            {
                return _DNS;
            }
            set
            {
                OnDNSChanging(value);
                ReportPropertyChanging("DNS");
                _DNS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DNS");
                OnDNSChanged();
            }
        }
        private global::System.String _DNS;
        partial void OnDNSChanging(global::System.String value);
        partial void OnDNSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HostLocation
        {
            get
            {
                return _HostLocation;
            }
            set
            {
                OnHostLocationChanging(value);
                ReportPropertyChanging("HostLocation");
                _HostLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HostLocation");
                OnHostLocationChanged();
            }
        }
        private global::System.String _HostLocation;
        partial void OnHostLocationChanging(global::System.String value);
        partial void OnHostLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="token")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class token : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 token 对象。
        /// </summary>
        /// <param name="token1">Token 属性的初始值。</param>
        public static token Createtoken(global::System.String token1)
        {
            token token = new token();
            token.Token = token1;
            return token;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                if (_Token != value)
                {
                    OnTokenChanging(value);
                    ReportPropertyChanging("Token");
                    _Token = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Token");
                    OnTokenChanged();
                }
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MacAddr
        {
            get
            {
                return _MacAddr;
            }
            set
            {
                OnMacAddrChanging(value);
                ReportPropertyChanging("MacAddr");
                _MacAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MacAddr");
                OnMacAddrChanged();
            }
        }
        private global::System.String _MacAddr;
        partial void OnMacAddrChanging(global::System.String value);
        partial void OnMacAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpiredDate
        {
            get
            {
                return _ExpiredDate;
            }
            set
            {
                OnExpiredDateChanging(value);
                ReportPropertyChanging("ExpiredDate");
                _ExpiredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpiredDate");
                OnExpiredDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpiredDate;
        partial void OnExpiredDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpiredDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IPDetectServer.Repositories.dbModels", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userType">UserType 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="fullName">FullName 属性的初始值。</param>
        public static User CreateUser(global::System.Int32 id, global::System.Int32 userType, global::System.String userName, global::System.String password, global::System.String fullName)
        {
            User user = new User();
            user.ID = id;
            user.UserType = userType;
            user.UserName = userName;
            user.Password = password;
            user.FullName = fullName;
            return user;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserType
        {
            get
            {
                return _UserType;
            }
            set
            {
                OnUserTypeChanging(value);
                ReportPropertyChanging("UserType");
                _UserType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserType");
                OnUserTypeChanged();
            }
        }
        private global::System.Int32 _UserType;
        partial void OnUserTypeChanging(global::System.Int32 value);
        partial void OnUserTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedDateChanged();

        #endregion

    
    }

    #endregion

    
}
